sudo: required
services:
- docker
dist: trusty
notifications:
  email:
    on_failure: change
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
deploy:
  provider: script
  script: make release
  skip_cleanup: true
  on:
    tags: true

